name: Node.js Package

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: cd sample-packages/npm && npm install
      - run: cd sample-packages/npm && npm ci
      - run: cd sample-packages/npm && npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: cd sample-packages/npm && npm install
      - run: cd sample-packages/npm && npm ci
      - run: cd sample-packages/npm && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
